name: "tagged-release"

on:
  push:
    paths:
      - 'manifest.json'

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2 # Ensure we can get the previous version

      - name: "Read versions from manifest"
        id: read-versions
        run: |
          version=$(sed -n 's/.*"version": "\(.*\)",/\1/p' manifest.json)
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "Version: $version"
          previous_version=$(git show HEAD^:manifest.json | sed -n 's/.*"version": "\(.*\)",/\1/p')
          echo "previous-version=$previous_version" >> "$GITHUB_OUTPUT"
          echo "Previous version: $previous_version"

      - name: "Zip release files" # Only if the version has been updated
        if: ${{ steps.read-versions.outputs.version != steps.read-versions.outputs.previous-version }}
        run: |
          echo "Creating a release zip file..."
          zip -r purlfy-release.zip icons/ main.js manifest.json preload.js renderer.js rules.json settings.html
          echo "Done!"

      - name: "Create Release"
        if: ${{ steps.read-versions.outputs.version != steps.read-versions.outputs.previous-version }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${{ steps.read-versions.outputs.version }}"
          title: "v${{ steps.read-versions.outputs.version }}"
          files: |
            purlfy-release.zip
